module.exports = Views = {}
Views.Fa = require './fa'
Views.FreeText = require './free-text'
Views.InOrder = require './in-order'
Views.MultipleChoices = require './multiple_choices'
Views.Ox = require './ox'
Views.SingleChoice = require './single_choice'
# Generated by IndexCoffeeGenerator