module.exports = Views = {}
Views.Fa = require './fa'
Views.FreeText = require './free-text'
Views.InOrder = require './in-order'
Views.Loading = require './loading'
Views.MultipleChoices = require './multiple_choices'
Views.Ox = require './ox'
Views.Paginator = require './paginator'
Views.SingleChoice = require './single_choice'
Views.TagSelector = require './tag-selector'
# Generated by IndexCoffeeGenerator