window.React   = require 'react'
window.ReactDOM   = require 'react-dom'
window.Promise = require 'bluebird'
window.Arda = require 'arda'
window._ = require 'lodash'
require './vendor/history-ward.min.js'
